name: flutter_get_api
description: A new Flutter project.
version: 1.1.0+2
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # TODO 01
  # Tambahkan dependencies http untuk dapat mengambil data dari API
  # Untuk melihat versi terbaru kamu bisa cek di https://pub.dev/packages/http
  http: ^0.13.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
flutter:
  uses-material-design: true
